// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/foundation/spaceservice"
)

var localSpaceClient spaceservice.Client

// GetSpace .
// @router /api/foundation/v1/spaces/:space_id [GET]
func GetSpace(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localSpaceClient.GetSpace)
}

// ListUserSpaces .
// @router /api/foundation/v1/spaces/list [POST]
func ListUserSpaces(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localSpaceClient.ListUserSpaces)
}
