// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/apis/llmmanageservice"
)

var llmManageSvc llmmanageservice.Client

// GetModel .
// @router /api/llm/v1/model/:model_id [POST]
func GetModel(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, llmManageSvc.GetModel)
}

// ListModels .
// @router /api/llm/v1/models/list [POST]
func ListModels(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, llmManageSvc.ListModels)
}
