// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/prompt/openapi/promptopenapiservice"
)

var promptOpenAPISvc promptopenapiservice.Client

// BatchGetPromptByPromptKey .
// @router /v1/loop/prompts/mget [POST]
func BatchGetPromptByPromptKey(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, promptOpenAPISvc.BatchGetPromptByPromptKey)
}
