// Copyright (c) 2025 coze-dev Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/data/tagservice"
)

var localTagClient tagservice.Client

// CreateTag .
// @router /api/data/v1/tags [POST]
func CreateTag(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.CreateTag)
}

// UpdateTag .
// @router /api/data/v1/tags/:tag_key_id [PATCH]
func UpdateTag(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.UpdateTag)
}

// BatchUpdateTagStatus .
// @router /api/data/v1/tags/batch_update_status [POST]
func BatchUpdateTagStatus(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.BatchUpdateTagStatus)
}

// SearchTags .
// @router /api/data/v1/tags/search [POST]
func SearchTags(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.SearchTags)
}

// GetTagDetail .
// @router /api/data/v1/tags/:tag_key_id/detail [GET]
func GetTagDetail(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.GetTagDetail)
}

// GetTagSpec .
// @router /api/data/v1/tag_spec [GET]
func GetTagSpec(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.GetTagSpec)
}

// BatchGetTags .
// @router /api/data/v1/tags/batch_get [POST]
func BatchGetTags(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.BatchGetTags)
}

// ArchiveOptionTag .
// @router /api/data/v1/tags/:tag_key_id/archive_option_tag [POST]
func ArchiveOptionTag(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localTagClient.ArchiveOptionTag)
}
