// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"github.com/coze-dev/cozeloop/backend/api/handler/coze/loop/apis"
	coze_loop_apis "github.com/coze-dev/cozeloop/backend/api/router/coze/loop/apis"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz, handler *apis.APIHandler) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	coze_loop_apis.Register(r, handler)
}
