// Code generated by Kitex v0.13.1. DO NOT EDIT.

package llmmanageservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	manage "github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/llm/manage"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ListModels(ctx context.Context, req *manage.ListModelsRequest, callOptions ...callopt.Option) (r *manage.ListModelsResponse, err error)
	GetModel(ctx context.Context, req *manage.GetModelRequest, callOptions ...callopt.Option) (r *manage.GetModelResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kLLMManageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLLMManageServiceClient struct {
	*kClient
}

func (p *kLLMManageServiceClient) ListModels(ctx context.Context, req *manage.ListModelsRequest, callOptions ...callopt.Option) (r *manage.ListModelsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListModels(ctx, req)
}

func (p *kLLMManageServiceClient) GetModel(ctx context.Context, req *manage.GetModelRequest, callOptions ...callopt.Option) (r *manage.GetModelResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetModel(ctx, req)
}
