// Code generated by Validator v0.2.6. DO NOT EDIT.

package prompt

import (
	"bytes"
	"fmt"
	"reflect"
	"regexp"
	"strings"
	"time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (p *Prompt) IsValid() error {
	if p.PromptBasic != nil {
		if err := p.PromptBasic.IsValid(); err != nil {
			return fmt.Errorf("field PromptBasic not valid, %w", err)
		}
	}
	if p.PromptDraft != nil {
		if err := p.PromptDraft.IsValid(); err != nil {
			return fmt.Errorf("field PromptDraft not valid, %w", err)
		}
	}
	if p.PromptCommit != nil {
		if err := p.PromptCommit.IsValid(); err != nil {
			return fmt.Errorf("field PromptCommit not valid, %w", err)
		}
	}
	return nil
}
func (p *PromptBasic) IsValid() error {
	return nil
}
func (p *PromptCommit) IsValid() error {
	if p.Detail != nil {
		if err := p.Detail.IsValid(); err != nil {
			return fmt.Errorf("field Detail not valid, %w", err)
		}
	}
	if p.CommitInfo != nil {
		if err := p.CommitInfo.IsValid(); err != nil {
			return fmt.Errorf("field CommitInfo not valid, %w", err)
		}
	}
	return nil
}
func (p *CommitInfo) IsValid() error {
	return nil
}
func (p *PromptDraft) IsValid() error {
	if p.Detail != nil {
		if err := p.Detail.IsValid(); err != nil {
			return fmt.Errorf("field Detail not valid, %w", err)
		}
	}
	if p.DraftInfo != nil {
		if err := p.DraftInfo.IsValid(); err != nil {
			return fmt.Errorf("field DraftInfo not valid, %w", err)
		}
	}
	return nil
}
func (p *DraftInfo) IsValid() error {
	return nil
}
func (p *PromptDetail) IsValid() error {
	if p.PromptTemplate != nil {
		if err := p.PromptTemplate.IsValid(); err != nil {
			return fmt.Errorf("field PromptTemplate not valid, %w", err)
		}
	}
	if p.ToolCallConfig != nil {
		if err := p.ToolCallConfig.IsValid(); err != nil {
			return fmt.Errorf("field ToolCallConfig not valid, %w", err)
		}
	}
	if p.ModelConfig != nil {
		if err := p.ModelConfig.IsValid(); err != nil {
			return fmt.Errorf("field ModelConfig not valid, %w", err)
		}
	}
	return nil
}
func (p *PromptTemplate) IsValid() error {
	return nil
}
func (p *Tool) IsValid() error {
	if p.Function != nil {
		if err := p.Function.IsValid(); err != nil {
			return fmt.Errorf("field Function not valid, %w", err)
		}
	}
	return nil
}
func (p *Function) IsValid() error {
	return nil
}
func (p *ToolCallConfig) IsValid() error {
	return nil
}
func (p *ModelConfig) IsValid() error {
	return nil
}
func (p *Message) IsValid() error {
	return nil
}
func (p *ContentPart) IsValid() error {
	if p.ImageURL != nil {
		if err := p.ImageURL.IsValid(); err != nil {
			return fmt.Errorf("field ImageURL not valid, %w", err)
		}
	}
	return nil
}
func (p *ImageURL) IsValid() error {
	return nil
}
func (p *ToolCall) IsValid() error {
	if p.FunctionCall != nil {
		if err := p.FunctionCall.IsValid(); err != nil {
			return fmt.Errorf("field FunctionCall not valid, %w", err)
		}
	}
	return nil
}
func (p *FunctionCall) IsValid() error {
	return nil
}
func (p *VariableDef) IsValid() error {
	return nil
}
func (p *VariableVal) IsValid() error {
	return nil
}
func (p *TokenUsage) IsValid() error {
	return nil
}
func (p *DebugContext) IsValid() error {
	if p.DebugCore != nil {
		if err := p.DebugCore.IsValid(); err != nil {
			return fmt.Errorf("field DebugCore not valid, %w", err)
		}
	}
	if p.DebugConfig != nil {
		if err := p.DebugConfig.IsValid(); err != nil {
			return fmt.Errorf("field DebugConfig not valid, %w", err)
		}
	}
	if p.CompareConfig != nil {
		if err := p.CompareConfig.IsValid(); err != nil {
			return fmt.Errorf("field CompareConfig not valid, %w", err)
		}
	}
	return nil
}
func (p *DebugCore) IsValid() error {
	return nil
}
func (p *CompareConfig) IsValid() error {
	return nil
}
func (p *CompareGroup) IsValid() error {
	if p.PromptDetail != nil {
		if err := p.PromptDetail.IsValid(); err != nil {
			return fmt.Errorf("field PromptDetail not valid, %w", err)
		}
	}
	if p.DebugCore != nil {
		if err := p.DebugCore.IsValid(); err != nil {
			return fmt.Errorf("field DebugCore not valid, %w", err)
		}
	}
	return nil
}
func (p *DebugMessage) IsValid() error {
	return nil
}
func (p *DebugToolCall) IsValid() error {
	if p.ToolCall != nil {
		if err := p.ToolCall.IsValid(); err != nil {
			return fmt.Errorf("field ToolCall not valid, %w", err)
		}
	}
	return nil
}
func (p *MockTool) IsValid() error {
	return nil
}
func (p *DebugConfig) IsValid() error {
	return nil
}
func (p *DebugLog) IsValid() error {
	return nil
}
func (p *OverridePromptParams) IsValid() error {
	if p.ModelConfig != nil {
		if err := p.ModelConfig.IsValid(); err != nil {
			return fmt.Errorf("field ModelConfig not valid, %w", err)
		}
	}
	return nil
}
