// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/modules/data/domain/tag/service (interfaces: ITagService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/tag_service_mock.go -package=mocks . ITagService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/coze-dev/coze-loop/backend/infra/db"
	entity "github.com/coze-dev/coze-loop/backend/modules/data/domain/tag/entity"
	pagination "github.com/coze-dev/coze-loop/backend/modules/data/pkg/pagination"
	gomock "go.uber.org/mock/gomock"
)

// MockITagService is a mock of ITagService interface.
type MockITagService struct {
	ctrl     *gomock.Controller
	recorder *MockITagServiceMockRecorder
}

// MockITagServiceMockRecorder is the mock recorder for MockITagService.
type MockITagServiceMockRecorder struct {
	mock *MockITagService
}

// NewMockITagService creates a new mock instance.
func NewMockITagService(ctrl *gomock.Controller) *MockITagService {
	mock := &MockITagService{ctrl: ctrl}
	mock.recorder = &MockITagServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITagService) EXPECT() *MockITagServiceMockRecorder {
	return m.recorder
}

// BatchGetTagsByTagKeyIDs mocks base method.
func (m *MockITagService) BatchGetTagsByTagKeyIDs(arg0 context.Context, arg1 int64, arg2 []int64) ([]*entity.TagKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetTagsByTagKeyIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.TagKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetTagsByTagKeyIDs indicates an expected call of BatchGetTagsByTagKeyIDs.
func (mr *MockITagServiceMockRecorder) BatchGetTagsByTagKeyIDs(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetTagsByTagKeyIDs", reflect.TypeOf((*MockITagService)(nil).BatchGetTagsByTagKeyIDs), arg0, arg1, arg2)
}

// BatchUpdateTagStatus mocks base method.
func (m *MockITagService) BatchUpdateTagStatus(arg0 context.Context, arg1 int64, arg2 []int64, arg3 entity.TagStatus) (map[int64]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchUpdateTagStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(map[int64]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchUpdateTagStatus indicates an expected call of BatchUpdateTagStatus.
func (mr *MockITagServiceMockRecorder) BatchUpdateTagStatus(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchUpdateTagStatus", reflect.TypeOf((*MockITagService)(nil).BatchUpdateTagStatus), arg0, arg1, arg2, arg3)
}

// CreateTag mocks base method.
func (m *MockITagService) CreateTag(arg0 context.Context, arg1 int64, arg2 *entity.TagKey, arg3 ...db.Option) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTag", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockITagServiceMockRecorder) CreateTag(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockITagService)(nil).CreateTag), varargs...)
}

// GetAllTagKeyVersionsByKeyID mocks base method.
func (m *MockITagService) GetAllTagKeyVersionsByKeyID(arg0 context.Context, arg1, arg2 int64, arg3 ...db.Option) ([]*entity.TagKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllTagKeyVersionsByKeyID", varargs...)
	ret0, _ := ret[0].([]*entity.TagKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTagKeyVersionsByKeyID indicates an expected call of GetAllTagKeyVersionsByKeyID.
func (mr *MockITagServiceMockRecorder) GetAllTagKeyVersionsByKeyID(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTagKeyVersionsByKeyID", reflect.TypeOf((*MockITagService)(nil).GetAllTagKeyVersionsByKeyID), varargs...)
}

// GetAndBuildTagValues mocks base method.
func (m *MockITagService) GetAndBuildTagValues(arg0 context.Context, arg1, arg2 int64, arg3 int32, arg4 ...db.Option) ([]*entity.TagValue, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAndBuildTagValues", varargs...)
	ret0, _ := ret[0].([]*entity.TagValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndBuildTagValues indicates an expected call of GetAndBuildTagValues.
func (mr *MockITagServiceMockRecorder) GetAndBuildTagValues(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndBuildTagValues", reflect.TypeOf((*MockITagService)(nil).GetAndBuildTagValues), varargs...)
}

// GetLatestTag mocks base method.
func (m *MockITagService) GetLatestTag(arg0 context.Context, arg1, arg2 int64, arg3 ...db.Option) (*entity.TagKey, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2}
	for _, a := range arg3 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLatestTag", varargs...)
	ret0, _ := ret[0].(*entity.TagKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestTag indicates an expected call of GetLatestTag.
func (mr *MockITagServiceMockRecorder) GetLatestTag(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2}, arg3...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestTag", reflect.TypeOf((*MockITagService)(nil).GetLatestTag), varargs...)
}

// GetTagDetail mocks base method.
func (m *MockITagService) GetTagDetail(arg0 context.Context, arg1 int64, arg2 *entity.GetTagDetailReq) (*entity.GetTagDetailResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagDetail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.GetTagDetailResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagDetail indicates an expected call of GetTagDetail.
func (mr *MockITagServiceMockRecorder) GetTagDetail(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagDetail", reflect.TypeOf((*MockITagService)(nil).GetTagDetail), arg0, arg1, arg2)
}

// GetTagSpec mocks base method.
func (m *MockITagService) GetTagSpec(arg0 context.Context, arg1 int64) (int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagSpec", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetTagSpec indicates an expected call of GetTagSpec.
func (mr *MockITagServiceMockRecorder) GetTagSpec(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagSpec", reflect.TypeOf((*MockITagService)(nil).GetTagSpec), arg0, arg1)
}

// SearchTags mocks base method.
func (m *MockITagService) SearchTags(arg0 context.Context, arg1 int64, arg2 *entity.MGetTagKeyParam) ([]*entity.TagKey, *pagination.PageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTags", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entity.TagKey)
	ret1, _ := ret[1].(*pagination.PageResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchTags indicates an expected call of SearchTags.
func (mr *MockITagServiceMockRecorder) SearchTags(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTags", reflect.TypeOf((*MockITagService)(nil).SearchTags), arg0, arg1, arg2)
}

// UpdateTag mocks base method.
func (m *MockITagService) UpdateTag(arg0 context.Context, arg1, arg2 int64, arg3 *entity.TagKey, arg4 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3}
	for _, a := range arg4 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTag", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockITagServiceMockRecorder) UpdateTag(arg0, arg1, arg2, arg3 any, arg4 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3}, arg4...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockITagService)(nil).UpdateTag), varargs...)
}

// UpdateTagStatus mocks base method.
func (m *MockITagService) UpdateTagStatus(arg0 context.Context, arg1, arg2 int64, arg3 int32, arg4 entity.TagStatus, arg5, arg6 bool, arg7 ...db.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1, arg2, arg3, arg4, arg5, arg6}
	for _, a := range arg7 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateTagStatus", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTagStatus indicates an expected call of UpdateTagStatus.
func (mr *MockITagServiceMockRecorder) UpdateTagStatus(arg0, arg1, arg2, arg3, arg4, arg5, arg6 any, arg7 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1, arg2, arg3, arg4, arg5, arg6}, arg7...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTagStatus", reflect.TypeOf((*MockITagService)(nil).UpdateTagStatus), varargs...)
}

// UpdateTagStatusWithNewVersion mocks base method.
func (m *MockITagService) UpdateTagStatusWithNewVersion(arg0 context.Context, arg1, arg2 int64, arg3 entity.TagStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTagStatusWithNewVersion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTagStatusWithNewVersion indicates an expected call of UpdateTagStatusWithNewVersion.
func (mr *MockITagServiceMockRecorder) UpdateTagStatusWithNewVersion(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTagStatusWithNewVersion", reflect.TypeOf((*MockITagService)(nil).UpdateTagStatusWithNewVersion), arg0, arg1, arg2, arg3)
}
