// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/coze-loop/backend/infra/mq (interfaces: IFactory)
//
// Generated by this command:
//
//	mockgen -destination=mocks/factory.go -package=mocks . IFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	mq "github.com/coze-dev/coze-loop/backend/infra/mq"
	gomock "go.uber.org/mock/gomock"
)

// MockIFactory is a mock of IFactory interface.
type MockIFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIFactoryMockRecorder
	isgomock struct{}
}

// MockIFactoryMockRecorder is the mock recorder for MockIFactory.
type MockIFactoryMockRecorder struct {
	mock *MockIFactory
}

// NewMockIFactory creates a new mock instance.
func NewMockIFactory(ctrl *gomock.Controller) *MockIFactory {
	mock := &MockIFactory{ctrl: ctrl}
	mock.recorder = &MockIFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFactory) EXPECT() *MockIFactoryMockRecorder {
	return m.recorder
}

// NewConsumer mocks base method.
func (m *MockIFactory) NewConsumer(arg0 mq.ConsumerConfig) (mq.IConsumer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConsumer", arg0)
	ret0, _ := ret[0].(mq.IConsumer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConsumer indicates an expected call of NewConsumer.
func (mr *MockIFactoryMockRecorder) NewConsumer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConsumer", reflect.TypeOf((*MockIFactory)(nil).NewConsumer), arg0)
}

// NewProducer mocks base method.
func (m *MockIFactory) NewProducer(arg0 mq.ProducerConfig) (mq.IProducer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProducer", arg0)
	ret0, _ := ret[0].(mq.IProducer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewProducer indicates an expected call of NewProducer.
func (mr *MockIFactoryMockRecorder) NewProducer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProducer", reflect.TypeOf((*MockIFactory)(nil).NewProducer), arg0)
}
