// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coze-dev/cozeloop/backend/modules/observability/domain/component/rpc (interfaces: IFileProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/file.go -package=mocks . IFileProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIFileProvider is a mock of IFileProvider interface.
type MockIFileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIFileProviderMockRecorder
	isgomock struct{}
}

// MockIFileProviderMockRecorder is the mock recorder for MockIFileProvider.
type MockIFileProviderMockRecorder struct {
	mock *MockIFileProvider
}

// NewMockIFileProvider creates a new mock instance.
func NewMockIFileProvider(ctrl *gomock.Controller) *MockIFileProvider {
	mock := &MockIFileProvider{ctrl: ctrl}
	mock.recorder = &MockIFileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFileProvider) EXPECT() *MockIFileProviderMockRecorder {
	return m.recorder
}

// GetDownloadUrls mocks base method.
func (m *MockIFileProvider) GetDownloadUrls(arg0 context.Context, arg1 string, arg2 []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownloadUrls", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDownloadUrls indicates an expected call of GetDownloadUrls.
func (mr *MockIFileProviderMockRecorder) GetDownloadUrls(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownloadUrls", reflect.TypeOf((*MockIFileProvider)(nil).GetDownloadUrls), arg0, arg1, arg2)
}
