// Code generated by Kitex v0.13.1. DO NOT EDIT.

package foundation

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/cloudwego/gopkg/protocol/thrift"

	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/auth"
	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/authn"
	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/file"
	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/openapi"
	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/space"
	"github.com/coze-dev/cozeloop/backend/kitex_gen/coze/loop/foundation/user"
)

var (
	_ = auth.KitexUnusedProtection
	_ = authn.KitexUnusedProtection
	_ = file.KitexUnusedProtection
	_ = openapi.KitexUnusedProtection
	_ = space.KitexUnusedProtection
	_ = user.KitexUnusedProtection
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = thrift.STOP
)
