CREATE TABLE IF NOT EXISTS `tag_key` (
    `id` bigint unsigned NOT NULL COMMENT '主键id',
    `app_id` int NOT NULL DEFAULT '0' COMMENT 'application id',
    `space_id` bigint unsigned NOT NULL COMMENT '归属space id,做分片键',
    `version_num` int NOT NULL DEFAULT '0' COMMENT 'tag自增版本',
    `version` varchar(64) NOT NULL COMMENT 'tag版本文案',
    `tag_key_id` bigint unsigned NOT NULL COMMENT 'tag id，唯一标识一个标签',
    `tag_key_name` varchar(255) NOT NULL COMMENT 'tag名称',
    `description` varchar(2000) DEFAULT NULL COMMENT 'tag描述',
    `parent_key_id` bigint unsigned DEFAULT NULL COMMENT '级联标签场景,上层tag key id',
    `created_at` timestamp NOT NULL COMMENT '创建时间',
    `updated_at` timestamp NOT NULL COMMENT '更新时间',
    `change_log` json NOT NULL COMMENT '变更日志',
    `status` varchar(32) NOT NULL DEFAULT '' COMMENT 'tag状态,active,inactive,deprecated',
    `tag_type` varchar(32) NOT NULL DEFAULT '' COMMENT 'tag类型,tag,option',
    `created_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `updated_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `tag_target_type` varchar(256) NOT NULL DEFAULT '' COMMENT 'tag目标对象列表,resource|dataset_item,多个值由,分隔',
    `content_type` varchar(64) NOT NULL DEFAULT 'categorical' COMMENT '内容类型: 自由文本,连续分值,分类,布尔值',
    `spec` json COMMENT '标签规格',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_space_id_tag_key_id_version_num_tag_type` (`space_id`,`tag_key_id`,`version_num`,`tag_type`),
    KEY `idx_space_id_tag_type_status_tag_key_name` (`space_id`,`tag_type`,`status`,`tag_key_name`),
    KEY `idx_space_id_tag_type_status_tag_created_by_tag_key_name` (`space_id`,`tag_type`,`status`,`created_by`,`tag_key_name`),
    KEY `idx_space_id_tag_type_status_content_type` (`space_id`,`tag_type`,`status`,`content_type`),
    KEY `idx_space_id_tag_type_status_updated_at` (`space_id`,`tag_type`,`status`,`updated_at`),
    KEY `idx_space_id_tag_type_status_created_at` (`space_id`,`tag_type`,`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='tag元数据表'