// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameObservabilityView = "observability_view"

// ObservabilityView 观测视图信息
type ObservabilityView struct {
	ID           int64          `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                          // 主键ID
	EnterpriseID string         `gorm:"column:enterprise_id;type:varchar(200);not null;comment:企业id" json:"enterprise_id"`                                                // 企业id
	WorkspaceID  int64          `gorm:"column:workspace_id;type:bigint(20) unsigned;not null;index:idx_space_id_created_by,priority:1;comment:空间 ID" json:"workspace_id"` // 空间 ID
	ViewName     string         `gorm:"column:view_name;type:varchar(256);not null;comment:视图名称" json:"view_name"`                                                        // 视图名称
	PlatformType string         `gorm:"column:platform_type;type:varchar(128);not null;comment:数据来源" json:"platform_type"`                                                // 数据来源
	SpanListType string         `gorm:"column:span_list_type;type:varchar(128);not null;comment:列表信息" json:"span_list_type"`                                              // 列表信息
	Filters      string         `gorm:"column:filters;type:varchar(2048);not null;comment:过滤条件信息" json:"filters"`                                                         // 过滤条件信息
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                // 创建时间
	CreatedBy    string         `gorm:"column:created_by;type:varchar(128);not null;index:idx_space_id_created_by,priority:2;comment:创建人" json:"created_by"`              // 创建人
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`                                // 修改时间
	UpdatedBy    string         `gorm:"column:updated_by;type:varchar(128);not null;comment:修改人" json:"updated_by"`                                                       // 修改人
	IsDeleted    bool           `gorm:"column:is_deleted;type:tinyint(1);not null;comment:是否删除, 0 表示未删除, 1 表示已删除" json:"is_deleted"`                                      // 是否删除, 0 表示未删除, 1 表示已删除
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                                                   // 删除时间
	DeletedBy    string         `gorm:"column:deleted_by;type:varchar(128);not null;comment:删除人" json:"deleted_by"`                                                       // 删除人
}

// TableName ObservabilityView's table name
func (*ObservabilityView) TableName() string {
	return TableNameObservabilityView
}
